= Why Gravitee.io ?
:page-sidebar: apim_3_x_sidebar
:page-permalink: apim/3.x/apim_overview_why.html
:page-folder: apim/overview
:page-toc: false
:page-layout: apim3x

At the very beginning, we were looking for an open-source solution to do API Management. Unfortunately, we've never found
the tool which fit exactly our needs and by choosing one of them we know that we have to pull other components and,
for some of them use a dedicated support.

That's the main reason why we launch Gravitee.io : our goal is to provide to users an highly integrable and scalable
solution which is able to fit perfectly their business requirements and infrastructure.

Also, Gravitee.io has been developed and designed to be fully extensible using its internal plugin system. You must be
able to do whatever you want : defining your own policy, developing your own reporting system, and so on...

Finally, all APIM components (including <<apim_overview_components.adoc#gravitee-components-gateway, API Gateway>> and <<apim_overview_components.adoc#gravitee-components-rest-api, APIM API>>) are really lightweight -- we
took an aggressive approach to CPU and memory management. This makes life much easier for you when it comes to high availability
with our blazing-fast component start-up times (it typically takes less than 5 seconds for the API Gateway
to be accessible to consumers, subject to the number of APIs being deployed).
